development:
adapter: postgresql
encoding: unicode
database: myapp_development
pool: 5
username: ale
password: qwerty123
test:
adapter: postgresql
encoding: unicode
database: myapp_test
pool: 5
username: ale
password: qwerty123
